### ISSUE TITLE
Undefined index: REQUEST_METHOD

### ISSUE THREAD

**Issue by mircobabini** [WPWhiteSecurity/wp-activity-log#554]
### Details

Version: latest

PHP Version: all

Server OS: CentOS

### What was expected to happen
No notice in debug.log, please :)

### What happened instead
PHP Notice:  Undefined index: REQUEST_METHOD in /wp-content/plugins/wp-security-audit-log/sdk/freemius/config.php on line 166

### Steps to reproduce this
call from crontab (php wp-cron.php...) or from WP_CLI

**Comment by mircobabini** [comment]
Also reported there => https://github.com/Freemius/wordpress-sdk/issues/452.

**Comment by robert81** [comment]
Fixed in latest update.

**Comment by mircobabini** [comment]
Hey @robert81, since the Freemius sdk still have the bug, how did you solve the issue? You are not requiring the sdk anymore when called from the cli?

Thanks.
